Create zh_tw_json
Snownee/SnowRealMagic pull request #72
Opened 2020-05-13 05:27 UTC by yappy2000d

2020-05-13 09:07 UTC, Snownee requested changes
File name is incorrect

2020-05-13 11:05 UTC, yappy2000d commented
OOPS!So awkward!LOL
I have done the change!
Hope you like it! :)

2020-05-15 18:33 UTC, Snownee commented
Thanks but the path is still no correct. I have added it manually.

2020-05-15 18:33 UTC, closed without merging

2020-05-15 21:02 UTC, yappy2000d commented
thx a lot!